# Based on https://github.com/CumulusNetworks/cldemo-vagrant/blob/master/Vagrantfile

Vagrant.configure("2") do |config|

  simid = 1531927274

  config.vm.provider "virtualbox" do |v|
    v.gui=false
  end

  ##### DEFINE VM for oob-mgmt-analytics #####
  config.vm.define "oob-mgmt-analytics" do |device|
    
    device.vm.hostname = "oob-mgmt-analytics"  
    device.vm.box = "bento/ubuntu-16.04"
    device.vm.provider "virtualbox" do |v|
      v.name = "#{simid}_oob-mgmt-analytics"
      v.customize ["modifyvm", :id, '--audiocontroller', 'AC97', '--audio', 'Null']
      v.memory = 4096
    end
    #   see note here: https://github.com/pradels/vagrant-libvirt#synced-folders
    device.vm.synced_folder ".", "/vagrant", disabled: false

    # NETWORK INTERFACES
      # link for eth1 --> oob-mgmt-switch:swp1
    device.vm.network "private_network", virtualbox__intnet: "#{simid}_net54", ip: "192.168.0.252"
    device.vm.network "forwarded_port", id: 'http', guest: 80, host: 80
    device.vm.provider "virtualbox" do |vbox|
      vbox.customize ['modifyvm', :id, '--nicpromisc2', 'allow-all']
      vbox.customize ["modifyvm", :id, "--nictype1", "virtio"]
    end
  end
end
