#16.04
box = "bento/ubuntu-16.04"

# Settings for all boxes:
Vagrant.configure("2") do |config|
    config.vm.box = box
    config.vm.provider "virtualbox" do |v|
      config.vbguest.auto_update = false
      v.customize ["modifyvm", :id, "--ostype", "Ubuntu_64"]
      v.customize ["modifyvm", :id, "--memory", "4096"]
    end

# Specific settings for box "vb-01":
  config.vm.define "vb-01" do |config|
    config.vm.host_name = "vb-01"
    config.vm.network "forwarded_port", id: 'ssh', guest: 22, host: 2222
    config.vm.network "private_network", ip: "192.168.56.5"
    config.vm.provision "shell", path: "ansible-control.sh"
    config.vm.provision "shell", inline: <<-SHELL
      echo -e '192.168.56.6\n192.168.56.7' >> /etc/ansible/hosts
      sudo sed -i 's/#host_key_checking/host_key_checking/g' /etc/ansible/ansible.cfg
    SHELL 
  end

# Specific settings for box "vb-02":
  config.vm.define "vb-02" do |config|
    config.vm.host_name = "vb-02"
    config.vm.network "forwarded_port", id: 'ssh', guest: 22, host: 2223
    config.vm.network "private_network", ip: "192.168.56.6"
    config.vm.provision "shell", path: "ansible-hosts.sh"
  end

# Specific settings for box "vb-03":
  config.vm.define "vb-03" do |config|
    config.vm.host_name = "vb-03"
    config.vm.network "forwarded_port", id: 'ssh', guest: 22, host: 2224
    config.vm.network "private_network", ip: "192.168.56.7"
    config.vm.provision "shell", path: "ansible-hosts.sh"
  end
    
end
