#14.04
box      = "trusty64"
url      = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"

#12.04
# box      = "precise64"
# url      = "https://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-amd64-vagrant-disk1.box"

hostname = "ub-01"

Vagrant.configure("2") do |config|
  config.vm.define "local-vb-01" do |config|
    config.vm.box = box
    config.vm.box_url = url
    config.vm.host_name = hostname
    config.vm.network "forwarded_port", id: 'ssh', guest: 22, host: 2222
#   config.vm.network "forwarded_port", id: 'http', guest: 9200, host: 9200
    config.vm.provider "virtualbox" do |v|
      v.gui = true
      v.customize ["modifyvm", :id, "--ostype", "Ubuntu_64"]
      v.customize ["modifyvm", :id, "--memory", "1024"]
      v.customize ["modifyvm", :id, "--vram", "16"]
      v.customize ["modifyvm", :id, "--nic2", "hostonly", "--nictype2", "82540EM", "--cableconnected2", "on", "--hostonlyadapter2", "vboxnet0"]
      v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
#     v.customize ["modifyvm", :id, "--accelerate3d", "on"]
      v.customize ["modifyvm", :id, "--accelerate2dvideo", "on"]
#     v.customize ["modifyvm", :id, "--audio", "dsound"]
    end
    config.vm.provision :shell, :path => "role_base.sh"
#   config.vm.provision :shell, :path => "desktop.sh"
  end

#  config.vm.define "local-vb-02" do |config|
#  end

#  config.vm.define "local-vb-03" do |config|
#  end

end
