VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.ssh.insert_key = false

  config.vm.define "ubuntu" do |vb|
    vb.vm.box = "ubuntu/trusty64"
    vb.vm.hostname = "ubuntu"
    vb.vm.network "private_network", ip: "10.1.0.101"
    vb.vm.provider :virtualbox do |vm|
      vm.memory = 2048
    end
    vb.vm.provision :ansible do |ansible|
      ansible.playbook = "play.yml"
      ansible.host_key_checking = false
    end
  end
end
